### ISSUE TITLE
"GET" no funciona

### ISSUE THREAD

**Issue by lluisgener** [lluis-mendoza/altech-test#1]
El método para obtener un producto por id siempre devuelve NotFound, tanto si lo encuentra como si no.

**Comment by lluis-galindo** [comment]
Hola! Había un bug con el parseo del Guid por parámetro de URL. Ya está solucionado. Muchas gracias!

**Comment by lluisgener** [comment]
El parseo lo vi bien, pero faltaba el return del OK, solo con eso ya me funcionó.

**Comment by lluis-galindo** [comment]
Cierto! Al utilizar hot reloading me generaba nuevos Guid y pensaba que era por el parseo. Pero también me he dado cuenta de este error.
